Practic/Models/Cookie.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Practic.Models
{
    public class Cookie
    {
        public int Id { get; set; }

        public string Image { get; set; }
        public string Header { get; set; }
        public string Main { get; set; }
        public string Footer { get; set; }

        [NotMapped]
        [Required]
        public IFormFile Photo { get; set; }

    }
}

Practic/Areas/AdminArea/Controllers/CookieController.cs
using FrontToBackEnd.Utilities.File;
using FrontToBackEnd.Utilities.Helpers;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using Practic.Data;
using Practic.Models;
using Practic.ViewModels.Admin.CookieViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Cookie = Practic.Models.Cookie;

namespace Practic.Areas.AdminArea.Controllers
{
    [Area("AdminArea")]
    public class CookieController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;
        public CookieController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public async Task<IActionResult> Index()
        {
            List<Cookie> cookies = await _context.Cookies.ToListAsync();
            return View(cookies);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CookieVM cookieVM)
        {

            if (ModelState["Images"].ValidationState == ModelValidationState.Invalid) return View();

            if (ModelState["Header"].ValidationState == ModelValidationState.Invalid) return View();

            if (ModelState["Main"].ValidationState == ModelValidationState.Invalid) return View();

            if (ModelState["Footer"].ValidationState == ModelValidationState.Invalid) return View();

            foreach (var photo in cookieVM.Images)
            {
                if (!photo.CheckFileType("image/"))
                {
                    ModelState.AddModelError("Photo", "Image type is wrong");
                    return View();
                }

                if (!photo.CheckFileSize(800))
                {
                    ModelState.AddModelError("Photo", "Image size is wrong");
                    return View();
                }

            }

            foreach (var photo in cookieVM.Images)
            {
                string fileName = Guid.NewGuid().ToString() + "_" + photo.FileName;


                string path = Helper.GetFilePath(_env.WebRootPath, "assets/img", fileName);

                using (FileStream stream = new FileStream(path, FileMode.Create))
                {
                    await photo.CopyToAsync(stream);
                }






                Cookie poster = new Cookie
                {
                    Image = fileName,
                    Header = cookieVM.Header,
                    Main = cookieVM.Main,
                    Footer = cookieVM.Footer

                };

                await _context.Cookies.AddAsync(poster);

            }








            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Practic/Areas/AdminArea/Views/Cookie/Create.cshtml
@model CookieVM
@{
    ViewData["Title"] = "Create";
   
}

<div class="container my-5">
    <form class="forms-sample mt-5" method="post" asp-action="Create" enctype="multipart/form-data">
        <div class="form-group">
            <label asp-for="Images"></label>
            <input class="form-control" style="width:300px" asp-for="Images">
            <span class="text-danger" asp-validation-for="Images"></span>
        </div>
        <div class="form-group">
            <label asp-for="Header">Header:</label>
            <input class="form-control" style="width:300px" asp-for="Header">
            <span class="text-danger" asp-validation-for="Header"></span>
        </div>
        <div class="form-group">
            <label asp-for="Main">Main:</label>
            <input class="form-control" style="width:300px" asp-for="Main">
            <span class="text-danger" asp-validation-for="Main"></span>
        </div>
        <div class="form-group">
            <label asp-for="Footer">Footer:</label>
            <input class="form-control" style="width:300px" asp-for="Footer">
            <span class="text-danger" asp-validation-for="Footer"></span>
        </div>
        <button type="submit" class="btn btn-primary me-2">Submit</button>
        <a asp-action="Index" class="btn btn-light">Cancel</a>
    </form>
</div>

Practic/Areas/AdminArea/Views/Cookie/Index.cshtml
@model List<Cookie>
@{
    ViewData["Title"] = "Index";
    
    int count = 1;
}

<div class="container">
    <div class="row">

        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <div class="header d-flex justify-content-between my-5">
                       
                        <div><a class="btn btn-success btn-sm my-4" asp-controller="Cookie" asp-action="Create">Create</a></div>




                    </div>
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th> No </th>
                                    <th> Image </th>
                                    <th> Discount </th>
                                    <th> Cookie </th>
                                    <th> WeekCount </th>
                                    <th> Setting </th>

                                </tr>
                            </thead>
                            <tbody>

                                @foreach (var cookie in Model)
                                {
                                    <tr>
                                        <td> @count </td>
                                        <td>   <img style="width:100px; height:50px; border-radius:unset" src="~/assets/img/@cookie.Image" alt="Poster" /></td>
                                        <td> @cookie.Header </td>
                                        <td>@cookie.Main  </td>
                                        <td> @cookie.Footer </td>
                                        <td>
                                            <a class="btn btn-primary btn-sm" asp-action="Detail" asp-route-Id="@cookie.Id"><i class="mdi mdi-account-card-details"></i></a>
                                            <a class="btn btn-inverse-warning btn-sm" asp-action="Edit" asp-route-Id="@cookie.Id"><i class="mdi mdi-grease-pencil"></i></a>
                                            <form style="display:inline;" asp-action="Delete" asp-route-Id="@cookie.Id">
                                                <button type="submit" class="btn btn-danger btn-sm"><i class="mdi mdi-delete-forever"></i></button>
                                            </form>
                                        </td>
                                    </tr>
                                    count++;
                                }






                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>